/*
 * Ported verbatim from the front end (`src/data/eventSeeds.ts`).
 *
 * The demonstration dataset is part of the product, not scaffolding: the
 * event copy, the plan benefits and the category colours are all content the
 * client reviews. Keeping one copy of it — the front end’s — and seeding the
 * database from that is what makes the connected application look exactly
 * like the prototype it replaces.
 */

import { VENUES } from './pools.js';

/**
 * Hand-written rather than generated: the events are the most-read copy in the
 * product, and a client demonstration lives or dies on whether they read like
 * real things a real organisation would run.
 */
export const EVENT_SEEDS = [
  /* ------------------------------------------------------------- completed */
  {
    slug: 'pongal-thiruvizha-2026',
    title: 'Pongal Thiruvizha 2026',
    summary:
      'The whole calendar builds to this one — cooking, kolam, music and about four hundred people in one courtyard.',
    description:
      'Pongal Thiruvizha is the largest thing Aarambam does all year, and the only event where we open the gates to the whole neighbourhood.\n\nThe morning starts with the pongal pots at 06:00 — bring your own if you would like to cook. The kolam competition is judged at 08:30, categories for under-12s and open. Folk performances run from 10:00, with the parai ensemble closing the morning.\n\nLunch is served on banana leaf from 12:30. Members eat first; there is always enough for everyone who comes.',
    categoryId: 'cat-cultural',
    venue: VENUES.communityHall,
    dayOffset: -198,
    startTime: '06:00',
    endTime: '15:00',
    capacity: 400,
    type: 'free',
    memberPrice: 0,
    nonMemberPrice: 0,
    fill: 0.94,
    opensBefore: 45,
  },
  {
    slug: 'republic-day-breakfast-2026',
    title: 'Republic Day Community Breakfast',
    summary: 'Flag hoisting at 08:00, breakfast at 08:30, done by ten.',
    description:
      'A short, unfussy morning. The flag goes up at 08:00 sharp, the school children sing, and then everybody eats.\n\nBreakfast is idli, pongal and vadai from the kitchen at the community hall. No tickets, no speeches longer than four minutes.',
    categoryId: 'cat-community',
    venue: VENUES.communityHall,
    dayOffset: -187,
    startTime: '08:00',
    endTime: '10:00',
    capacity: 180,
    type: 'free',
    memberPrice: 0,
    nonMemberPrice: 0,
    fill: 0.82,
  },
  {
    slug: 'spoken-english-batch-6',
    title: 'Spoken English for Beginners — Batch 6',
    summary: 'Eight Saturday mornings. Small group, lots of talking, no grammar drills.',
    description:
      'An eight-week course for members who can read English but freeze when they have to speak it. Batch size is capped at twenty-four so everyone gets time on their feet.\n\nSessions are built around situations rather than tenses — a phone call to a hospital, an interview, explaining a problem to a shopkeeper. Vidhya Ravichandran has run all six batches so far.\n\nThe fee covers the workbook. Attendance in at least six of the eight sessions is required for the completion certificate.',
    categoryId: 'cat-learning',
    venue: VENUES.learningCentre,
    dayOffset: -150,
    startTime: '09:00',
    endTime: '11:00',
    capacity: 24,
    type: 'paid',
    memberPrice: 600,
    nonMemberPrice: 1000,
    fill: 1,
  },
  {
    slug: 'beach-cleanup-elliots-feb',
    title: "Beach Clean-Up at Elliot's",
    summary: 'Two hours, gloves and bags provided, tea afterwards at the Ashtalakshmi end.',
    description:
      'We meet at the Karl Schmidt memorial at 06:30 and work north towards the temple. Gloves, sacks and grabbers are provided; wear shoes you do not mind ruining.\n\nSegregation happens on site — the Corporation truck collects at 09:00, so anything not sorted by then goes to landfill. Children under fourteen are welcome with a parent.',
    categoryId: 'cat-outreach',
    venue: VENUES.elliots,
    dayOffset: -120,
    startTime: '06:30',
    endTime: '09:00',
    capacity: 120,
    type: 'free',
    memberPrice: 0,
    nonMemberPrice: 0,
    fill: 0.63,
  },
  {
    slug: 'silambam-basics-workshop',
    title: 'Silambam Basics Workshop',
    summary: 'A first introduction to the staff — stance, grip and the four opening movements.',
    description:
      'Silambam is a Tamil martial art built around a bamboo staff. This is an absolute beginners’ session: no previous training assumed, no fitness requirement beyond being able to stand for ninety minutes.\n\nStaffs are provided. Wear loose cotton clothing. Under-16s need a guardian’s written consent, which you can complete at registration.',
    categoryId: 'cat-workshop',
    venue: VENUES.ymca,
    dayOffset: -96,
    startTime: '17:00',
    endTime: '19:00',
    capacity: 30,
    type: 'paid',
    memberPrice: 250,
    nonMemberPrice: 450,
    fill: 1,
  },
  {
    slug: 'aarambam-10k-2026',
    title: 'Aarambam 10K Run',
    summary: 'Flag-off at 05:30 from the YMCA gate. 10K and 5K routes, both timed.',
    description:
      'The fourth running of the Aarambam 10K. Two routes — the full 10K along the Adyar bank and back, and a 5K for first-timers and juniors.\n\nBibs and timing chips are collected the previous evening from the community hall between 17:00 and 20:00. Water at three points on the 10K, one on the 5K. Medical support at the start and finish.\n\nFinisher medals for everyone who crosses. Category prizes for the first three men and women on each route.',
    categoryId: 'cat-sports',
    venue: VENUES.ymca,
    dayOffset: -70,
    startTime: '05:30',
    endTime: '09:30',
    capacity: 250,
    type: 'paid',
    memberPrice: 300,
    nonMemberPrice: 500,
    fill: 0.88,
    opensBefore: 40,
  },
  {
    slug: 'career-guidance-class-12',
    title: 'Career Guidance Day for Class 12',
    summary:
      'Counsellors, an admissions panel and honest conversation about what the marks actually mean.',
    description:
      'For students who have just written their board exams, and for the parents who are more anxious than they are.\n\nThe morning is a panel — an engineering admissions officer, a working nurse, a chartered accountant and a serving district officer — on what their route actually looked like. The afternoon is one-to-one counselling in fifteen-minute slots, booked on the day.\n\nBring your marksheet if you have it. Entry is free for members’ children; others pay a nominal fee towards the counsellors’ costs.',
    categoryId: 'cat-youth',
    venue: VENUES.learningCentre,
    dayOffset: -52,
    startTime: '09:30',
    endTime: '16:00',
    capacity: 90,
    type: 'paid',
    memberPrice: 0,
    nonMemberPrice: 200,
    fill: 0.79,
  },
  {
    slug: 'mental-health-circle-june',
    title: 'Mental Health Circle — June',
    summary: 'A facilitated, confidential hour. No advice, no fixing, no attendance register.',
    description:
      'A monthly listening circle facilitated by a licensed counsellor. Twelve chairs, ninety minutes, and one rule: what is said here stays here.\n\nThis is not therapy and it is not a substitute for it. If you are in crisis, please call Sneha on 044 2464 0050 — they answer at any hour.\n\nRegistration is capped at twelve and names are not published in any participant list.',
    categoryId: 'cat-wellness',
    venue: VENUES.communityHall,
    dayOffset: -40,
    startTime: '18:30',
    endTime: '20:00',
    capacity: 12,
    type: 'free',
    memberPrice: 0,
    nonMemberPrice: 0,
    fill: 0.92,
  },
  {
    slug: 'members-meet-july-2026',
    title: 'Monthly Members’ Meet — July',
    summary: 'Accounts, what is coming up, and whatever members want to raise.',
    description:
      'The standing monthly meeting. The treasurer reads the month’s accounts, the events team runs through the next six weeks, and then the floor is open.\n\nAny member may raise an item. If you would like something minuted, send it to hello@aarambam.org at least two days before.',
    categoryId: 'cat-community',
    venue: VENUES.communityHall,
    dayOffset: -18,
    startTime: '18:30',
    endTime: '20:00',
    capacity: 120,
    type: 'free',
    memberPrice: 0,
    nonMemberPrice: 0,
    fill: 0.55,
  },
  {
    slug: 'photography-walk-george-town',
    title: 'Photography Walk — George Town',
    summary:
      'Four hours through the oldest streets in the city, ending at the harbour wall.',
    description:
      'We start at the Parry’s Corner clock tower at 06:00, while the wholesale markets are still working, and finish near the harbour by ten.\n\nAny camera, including a phone. The walk is led by Aravind Natarajan, who has photographed this quarter for eleven years and knows which shutters open when.\n\nAbout six kilometres on foot, mostly flat, on uneven pavement. Photographs from the walk are shared to the members’ gallery afterwards.',
    categoryId: 'cat-workshop',
    venue: VENUES.georgeTown,
    dayOffset: -9,
    startTime: '06:00',
    endTime: '10:00',
    capacity: 20,
    type: 'paid',
    memberPrice: 400,
    nonMemberPrice: 650,
    fill: 1,
  },

  /* -------------------------------------------------------------- upcoming */
  {
    slug: 'carnatic-vocal-rhythm-masterclass',
    title: 'Carnatic Vocal & Rhythm Masterclass',
    summary:
      'An intensive evening masterclass on raga structure and tala patterns led by Vidwan K. Ramesh.',
    description:
      'Join us for a 3-hour immersive session on Carnatic vocal ornamentation, improvisational neraval, and rhythm synchronization.\n\nOpen to intermediate learners and enthusiasts. The ticket includes a reference notation booklet and evening snacks.',
    categoryId: 'cat-cultural',
    venue: VENUES.communityHall,
    dayOffset: 5,
    startTime: '17:00',
    endTime: '20:00',
    capacity: 60,
    type: 'paid',
    memberPrice: 250,
    nonMemberPrice: 500,
    fill: 0.2,
    opensBefore: 30,
    closesBefore: 1,
  },
  {
    slug: 'members-meet-august-2026',
    title: 'Monthly Members’ Meet — August',
    summary: 'Accounts, what is coming up, and whatever members want to raise.',
    description:
      'The standing monthly meeting. The treasurer reads the month’s accounts, the events team runs through the next six weeks, and then the floor is open.\n\nThis month also includes a short briefing on the Annual General Meeting in October and the process for standing for the committee.',
    categoryId: 'cat-community',
    venue: VENUES.communityHall,
    dayOffset: 8,
    startTime: '18:30',
    endTime: '20:00',
    capacity: 120,
    type: 'free',
    memberPrice: 0,
    nonMemberPrice: 0,
    fill: 0.34,
  },
  {
    slug: 'pottery-and-clay-workshop',
    title: 'Pottery & Clay Workshop',
    summary: 'Wheel work for complete beginners. Everything you make gets fired and returned.',
    description:
      'A single Sunday on the wheel with Poongodi Arumugam, who has thrown pots in Thiruvanmiyur for two decades.\n\nClay, tools and an apron are provided. You will centre, open and pull at least one pot; most people manage three. Pieces are fired during the following week and can be collected from the community hall after the fifteenth.\n\nBring short nails and no rings. This session is limited to fourteen wheels.',
    categoryId: 'cat-workshop',
    venue: VENUES.learningCentre,
    dayOffset: 12,
    startTime: '10:00',
    endTime: '13:30',
    capacity: 14,
    type: 'paid',
    memberPrice: 750,
    nonMemberPrice: 1100,
    fill: 0,
  },
  {
    slug: 'weekend-yoga-breathwork',
    title: 'Weekend Yoga & Breathwork',
    summary: 'Sunday mornings in the park. Mats provided, all levels, no chanting.',
    description:
      'Ninety minutes on the lawn at Semmozhi Poonga — forty-five of movement, thirty of pranayama, fifteen of lying still.\n\nSuitable for complete beginners and for members returning after injury; the instructor gives a seated variation for every posture. Mats are provided but bring your own if you prefer.\n\nWe run rain or shine; if it rains we move under the pavilion.',
    categoryId: 'cat-wellness',
    venue: VENUES.semmozhiPoonga,
    dayOffset: 13,
    startTime: '06:30',
    endTime: '08:00',
    capacity: 45,
    type: 'paid',
    memberPrice: 150,
    nonMemberPrice: 300,
    fill: 0.6,
  },
  {
    slug: 'first-aid-cpr-certification',
    title: 'First Aid & CPR Certification',
    summary:
      'A full day, ending with an assessment and a two-year certificate that employers accept.',
    description:
      'Run in partnership with a St John Ambulance trainer. The syllabus covers primary survey, recovery position, adult and infant CPR, choking, bleeding, burns and fracture immobilisation.\n\nThe day ends with a practical assessment on the manikins. Everyone who passes receives a certificate valid for two years; everyone who does not may re-sit at the next running at no charge.\n\nWear clothes you can kneel in. Lunch is included.',
    categoryId: 'cat-learning',
    venue: VENUES.learningCentre,
    dayOffset: 20,
    startTime: '09:00',
    endTime: '17:00',
    capacity: 28,
    type: 'paid',
    memberPrice: 900,
    nonMemberPrice: 1400,
    fill: 0.86,
  },
  {
    slug: 'kabaddi-league-season-3',
    title: 'Kabaddi League — Season 3 Opening',
    summary: 'Eight teams, two mats, one evening. Spectators free, players register by team.',
    description:
      'The opening evening of the third Aarambam kabaddi league. Eight teams of twelve, drawn into two pools, playing across two mats from six o’clock.\n\nPlayers must register through their team captain and be paid-up members. Spectators do not need a ticket, but registering helps us plan seating.\n\nThe league runs over six Saturdays; the final is on the last weekend of November.',
    categoryId: 'cat-sports',
    venue: VENUES.indoorStadium,
    dayOffset: 27,
    startTime: '18:00',
    endTime: '21:30',
    capacity: 300,
    type: 'free',
    memberPrice: 0,
    nonMemberPrice: 0,
    fill: 0.41,
  },
  {
    slug: 'village-school-library-drive',
    title: 'Village School Library Drive',
    summary:
      'Sorting, cataloguing and shelving a donated library at Kattupakkam. Bring nothing but time.',
    description:
      'Around four thousand donated books are sitting in cartons at the Panchayat Union Middle School. This is the day we turn them into a library.\n\nWork is sorting by reading level, discarding what is damaged, writing accession numbers and shelving. Some of it is dusty. All of it is straightforward.\n\nTransport leaves the community hall at 07:30 and returns by 17:00 — reserve a seat when you register. Lunch is provided by the school.',
    categoryId: 'cat-outreach',
    venue: VENUES.villageSchool,
    dayOffset: 34,
    startTime: '08:30',
    endTime: '16:00',
    capacity: 60,
    type: 'free',
    memberPrice: 0,
    nonMemberPrice: 0,
    fill: 0.28,
  },
  {
    slug: 'bharatanatyam-evening-2026',
    title: 'Bharatanatyam Evening',
    summary:
      'Six dancers, live orchestra, one margam. The hall seats two hundred and it always fills.',
    description:
      'A full margam performed by six senior students of the Mylapore school, with live mridangam, violin, flute and nattuvangam.\n\nThe programme runs alarippu through to thillana with a short interval. Doors at 17:45; the hall is not admitted to once a piece has begun, so please arrive early.\n\nReserved seating for Premium members is in the first four rows and is held until 17:50.',
    categoryId: 'cat-cultural',
    venue: VENUES.mylaporeFineArts,
    dayOffset: 41,
    startTime: '18:00',
    endTime: '20:30',
    capacity: 200,
    type: 'paid',
    memberPrice: 200,
    nonMemberPrice: 400,
    fill: 0.97,
  },
  {
    slug: 'heritage-walk-mylapore',
    title: 'Heritage Walk — Mylapore',
    summary: 'Cancelled. The tank restoration work has closed the route until December.',
    description:
      'A morning walk around the Kapaleeshwarar tank and the streets behind it, looking at the agraharam houses, the tank steps and the four car streets.\n\nThis walk has been cancelled: the Corporation’s tank desilting work has closed the north and west steps and there is no safe alternative route. We will run it again once the work is finished.',
    categoryId: 'cat-workshop',
    venue: VENUES.mylaporeFineArts,
    dayOffset: 48,
    startTime: '06:30',
    endTime: '09:00',
    capacity: 25,
    type: 'paid',
    memberPrice: 300,
    nonMemberPrice: 500,
    lifecycle: 'cancelled',
    fill: 0.72,
    cancellationReason:
      'Tank desilting work has closed the north and west steps; there is no safe alternative route until December.',
  },
  {
    slug: 'summer-coding-camp-teens',
    title: 'Coding Camp for Teens',
    summary:
      'Five days, ages 13–17. They arrive knowing nothing and leave with something that runs.',
    description:
      'A five-day camp for members’ children aged thirteen to seventeen. No prior programming experience is assumed or expected.\n\nDays one and two are the basics in Python. Day three is a micro:bit and a soldering iron. Days four and five are a project of their own choosing, presented to parents on the Friday evening.\n\nLaptops are provided — there are eighteen, which is why the cap is eighteen. Bring a water bottle and lunch.',
    categoryId: 'cat-youth',
    venue: VENUES.learningCentre,
    dayOffset: 55,
    startTime: '09:30',
    endTime: '16:00',
    capacity: 18,
    type: 'paid',
    memberPrice: 1500,
    nonMemberPrice: 2400,
    fill: 0.5,
  },
  {
    slug: 'annual-general-meeting-2026',
    title: 'Annual General Meeting 2026',
    summary:
      'Accounts for the year, the committee election, and the vote on next year’s subscription.',
    description:
      'The Annual General Meeting is open to every member; Premium members carry a vote.\n\nThe agenda is the audited accounts for 2025–26, the secretary’s report, the election of six committee places, and a resolution on subscription rates for the coming year.\n\nNominations for the committee close fourteen days before the meeting. Proxy forms are available from the office and must be lodged forty-eight hours in advance.',
    categoryId: 'cat-community',
    venue: VENUES.vaniMahal,
    dayOffset: 68,
    startTime: '17:00',
    endTime: '20:00',
    capacity: 350,
    type: 'free',
    memberPrice: 0,
    nonMemberPrice: 0,
    fill: 0.19,
    opensBefore: 50,
  },
  {
    slug: 'deepavali-cultural-night-2026',
    title: 'Deepavali Cultural Night',
    summary:
      'The big evening — music, a light installation across the courtyard, and food until it runs out.',
    description:
      'Aarambam’s Deepavali evening, held in the open courtyard at Vani Mahal.\n\nThe programme is a nadaswaram opening, a students’ showcase, and a two-hour set from a folk ensemble. Between them, a light installation runs the length of the courtyard, built by the youth programme over the preceding fortnight.\n\nNo crackers on the premises. Food stalls open at 18:00 and close when they are empty.',
    categoryId: 'cat-cultural',
    venue: VENUES.vaniMahal,
    dayOffset: 80,
    startTime: '17:30',
    endTime: '22:00',
    capacity: 500,
    type: 'paid',
    memberPrice: 150,
    nonMemberPrice: 350,
    fill: 0.12,
    opensBefore: 55,
  },
];
